# ------------------------------------------------------------------------
# RF-DETR
# Copyright (c) 2025 Roboflow. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 [see LICENSE for details]
# ------------------------------------------------------------------------
"""LightningCLI entry point for RF-DETR training and evaluation.

Provides the ``rfdetr`` command with auto-generated subcommands::

    rfdetr fit     --config configs/rfdetr_base.yaml
    rfdetr validate --ckpt_path output/best.ckpt
    rfdetr test    --ckpt_path output/best.ckpt
    rfdetr predict --ckpt_path output/best.ckpt

Both ``RFDETRModelModule`` and ``RFDETRDataModule`` share the same ``(model_config, train_config)`` constructor
signature.  ``link_arguments`` eliminates the duplication so the user specifies each config group once; the datamodule
receives the same values automatically at parse time.
"""

from typing import Any

from pytorch_lightning import Trainer
from pytorch_lightning.cli import LightningArgumentParser, LightningCLI

from rfdetr.training.module_data import RFDETRDataModule
from rfdetr.training.module_model import RFDETRModelModule
from rfdetr.training.trainer import build_trainer
from rfdetr.utilities.logger import get_logger


logger = get_logger()


_TRAINER_PASSTHROUGH_KEYS = (
    "devices",
    "num_nodes",
    "strategy",
    "fast_dev_run",
    "limit_train_batches",
    "limit_val_batches",
    "limit_test_batches",
    "limit_predict_batches",
    "overfit_batches",
    "val_check_interval",
    "check_val_every_n_epoch",
    "num_sanity_val_steps",
    "log_every_n_steps",
    "enable_checkpointing",
    "enable_model_summary",
    "profiler",
    "detect_anomaly",
    "barebones",
    "plugins",
    "reload_dataloaders_every_n_epochs",
    "default_root_dir",
)


class RFDETRCli(LightningCLI):
    """LightningCLI subclass for RF-DETR training and evaluation.

    Wires ``RFDETRModelModule`` and ``RFDETRDataModule`` under a unified CLI, with argument linking that shares
    ``model_config`` and ``train_config`` between module and datamodule so the user only specifies them once.

    Auto-generated subcommands: ``fit``, ``validate``, ``test``, ``predict``.
    """

    def add_arguments_to_parser(self, parser: LightningArgumentParser) -> None:
        """Register argument links that share configs between module and datamodule.

        Linking ``model.model_config`` → ``data.model_config`` and ``model.train_config`` → ``data.train_config`` means
        the user specifies both config groups once; the datamodule receives the same values automatically.

        Args:
            parser: The jsonargparse ``LightningArgumentParser`` provided by
                ``LightningCLI``.
        """
        parser.link_arguments("model.model_config", "data.model_config", apply_on="parse")
        parser.link_arguments("model.train_config", "data.train_config", apply_on="parse")

    def instantiate_trainer(self, **kwargs: Any) -> Trainer:
        """Instantiate the RF-DETR trainer from ``TrainConfig``.

        LightningCLI's default trainer construction only reads the top-level
        ``trainer`` section. RF-DETR's public configs put training semantics
        such as ``epochs``, ``grad_accum_steps``, callbacks, loggers, and EMA
        under ``model.train_config``. Route construction through
        :func:`rfdetr.training.trainer.build_trainer` so the CLI behaves like
        the Python ``RFDETR.train()`` path.

        Args:
            **kwargs: Extra trainer arguments supplied by LightningCLI internals.

        Returns:
            A configured PyTorch Lightning Trainer.
        """
        trainer_config = {**self._get(self.config_init, "trainer", default={}), **kwargs}
        trainer_kwargs = {
            key: trainer_config[key]
            for key in _TRAINER_PASSTHROUGH_KEYS
            if key in trainer_config and trainer_config[key] is not None
        }
        accelerator = trainer_config.get("accelerator")
        return build_trainer(
            self.model.train_config,
            self.model.model_config,
            accelerator=accelerator,
            **trainer_kwargs,
        )

    def before_fit(self) -> None:
        """Optionally run validation once before the first training step."""
        train_config = self.model.train_config
        if not getattr(train_config, "validate_before_fit", False):
            return
        ckpt_path = train_config.resume or None
        logger.info("Running validation before fit starts.")
        self.trainer.validate(self.model, self.datamodule, ckpt_path=ckpt_path)


def main() -> None:
    """Entry point for the ``rfdetr`` CLI.

    Constructs and runs ``RFDETRCli`` with ``RFDETRModelModule`` and ``RFDETRDataModule``.  Subcommands are auto-
    generated by ``LightningCLI``: ``fit``, ``validate``, ``test``, ``predict``.
    """
    RFDETRCli(RFDETRModelModule, RFDETRDataModule)


if __name__ == "__main__":
    main()
